### ISSUE TITLE
`Niski Przebieg` Bug

### ISSUE THREAD

**Issue by Atrolide** [Atrolide/MotoScraper#1]
Fix the issue where `Niski przebieg` is inserted into a 3rd column of a database and ommits the rest of the input.

**Comment by xd4niel** [comment]
Replace lines 38-53 with the code below:

`year = ''
 mileage = ''
 engine_size = ''
 fuel_type = ''
 for ad_list in ad_list_all:
            if 'Niski przebieg' in ad_list.text:
                continue
            if 'cm3' in ad_list.text:
                engine_size = ad_list.text.strip()
            elif 'km' in ad_list.text:
                mileage = ad_list.text.strip()
            elif ad_list.text.isnumeric():
                year = ad_list.text.strip()
            else:
                fuel_type = ad_list.text.strip()
`
